FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY realtime/web_dashboard.py .
COPY realtime/pages ./pages
EXPOSE 8501
CMD ["streamlit", "run", "web_dashboard.py", "--server.address=0.0.0.0"]